name: pyedm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - jupyter
  - ipykernel
  - pyyaml
  - joblib
  - pip
  - pip:
      - pyEDM
