file_name: "data_w_gaps_and_wind.csv"
parameters_path: "100_sample_baseline_models.csv"
target: "Avg_Chloro"
n: 300
p: 0.05
drive_id: "https://drive.google.com/file/d/1LzN-OFINR9J2thyiWeTfox4enmEqbfoq/"